pub mod model;
pub mod device;
pub mod group;
pub mod data;
pub mod buffer;
pub mod slice;
pub mod log;

// model service procedure names
const READ_MODEL: &str = "read_model";
const LIST_MODEL_BY_NAME: &str = "list_model_by_name";
const LIST_MODEL_BY_CATEGORY: &str = "list_model_by_category";
const LIST_MODEL_BY_NAME_CATEGORY: &str = "list_model_by_name_category";
const CREATE_MODEL: &str = "create_model";
const UPDATE_MODEL: &str = "update_model";
const DELETE_MODEL: &str = "delete_model";
const ADD_MODEL_TYPE: &str = "add_model_type";
const REMOVE_MODEL_TYPE: &str = "remove_model_type";
const READ_MODEL_CONFIG: &str = "read_model_config";
const LIST_MODEL_CONFIG: &str = "list_model_config";
const CREATE_MODEL_CONFIG: &str = "create_model_config";
const UPDATE_MODEL_CONFIG: &str = "update_model_config";
const DELETE_MODEL_CONFIG: &str = "delete_model_config";
// device service procedure names
const READ_DEVICE: &str = "read_device";
const READ_DEVICE_BY_SN: &str = "read_device_by_sn";
const LIST_DEVICE_BY_GATEWAY: &str = "list_device_by_gateway";
const LIST_DEVICE_BY_TYPE: &str = "list_device_by_type";
const LIST_DEVICE_BY_NAME: &str = "list_device_by_name";
const LIST_DEVICE_BY_GATEWAY_TYPE: &str = "list_device_by_gateway_type";
const LIST_DEVICE_BY_GATEWAY_NAME: &str = "list_device_by_gateway_name";
const CREATE_DEVICE: &str = "create_device";
const UPDATE_DEVICE: &str = "update_device";
const DELETE_DEVICE: &str = "delete_device";
const READ_GATEWAY: &str = "read_gateway";
const READ_GATEWAY_BY_SN: &str = "read_gateway_by_sn";
const LIST_GATEWAY_BY_TYPE: &str = "list_gateway_by_type";
const LIST_GATEWAY_BY_NAME: &str = "list_gateway_by_name";
const CREATE_GATEWAY: &str = "create_gateway";
const UPDATE_GATEWAY: &str = "update_gateway";
const DELETE_GATEWAY: &str = "delete_gateway";
const READ_DEVICE_CONFIG: &str = "read_device_config";
const LIST_DEVICE_CONFIG: &str = "list_device_config";
const CREATE_DEVICE_CONFIG: &str = "create_device_config";
const UPDATE_DEVICE_CONFIG: &str = "update_device_config";
const DELETE_DEVICE_CONFIG: &str = "delete_device_config";
const READ_GATEWAY_CONFIG: &str = "read_gateway_config";
const LIST_GATEWAY_CONFIG: &str = "list_gateway_config";
const CREATE_GATEWAY_CONFIG: &str = "create_gateway_config";
const UPDATE_GATEWAY_CONFIG: &str = "update_gateway_config";
const DELETE_GATEWAY_CONFIG: &str = "delete_gateway_config";
const READ_TYPE: &str = "read_type";
const LIST_TYPE_BY_NAME: &str = "list_type_by_name";
const CREATE_TYPE: &str = "create_type";
const UPDATE_TYPE: &str = "update_type";
const DELETE_TYPE: &str = "delete_type";
const ADD_TYPE_MODEL: &str = "add_type_model";
const REMOVE_TYPE_MODEL: &str = "remove_type_model";
// group service procedure names
const READ_GROUP_MODEL: &str = "read_group_model";
const LIST_GROUP_MODEL_BY_NAME: &str = "list_group_model_by_name";
const LIST_GROUP_MODEL_BY_CATEGORY: &str = "list_group_model_by_category";
const LIST_GROUP_MODEL_BY_NAME_CATEGORY: &str = "list_group_model_by_name_category";
const CREATE_GROUP_MODEL: &str = "create_group_model";
const UPDATE_GROUP_MODEL: &str = "update_group_model";
const DELETE_GROUP_MODEL: &str = "delete_group_model";
const ADD_GROUP_MODEL_MEMBER: &str = "add_group_model_member";
const REMOVE_GROUP_MODEL_MEMBER: &str = "remove_group_model_member";
const READ_GROUP_DEVICE: &str = "read_group_device";
const LIST_GROUP_DEVICE_BY_NAME: &str = "list_group_device_by_name";
const LIST_GROUP_DEVICE_BY_CATEGORY: &str = "list_group_device_by_category";
const LIST_GROUP_DEVICE_BY_NAME_CATEGORY: &str = "list_group_device_by_name_category";
const CREATE_GROUP_DEVICE: &str = "create_group_device";
const UPDATE_GROUP_DEVICE: &str = "update_group_device";
const DELETE_GROUP_DEVICE: &str = "delete_group_device";
const ADD_GROUP_DEVICE_MEMBER: &str = "add_group_device_member";
const REMOVE_GROUP_DEVICE_MEMBER: &str = "remove_group_device_member";
const READ_GROUP_GATEWAY: &str = "read_group_gateway";
const LIST_GROUP_GATEWAY_BY_NAME: &str = "list_group_gateway_by_name";
const LIST_GROUP_GATEWAY_BY_CATEGORY: &str = "list_group_gateway_by_category";
const LIST_GROUP_GATEWAY_BY_NAME_CATEGORY: &str = "list_group_gateway_by_name_category";
const CREATE_GROUP_GATEWAY: &str = "create_group_gateway";
const UPDATE_GROUP_GATEWAY: &str = "update_group_gateway";
const DELETE_GROUP_GATEWAY: &str = "delete_group_gateway";
const ADD_GROUP_GATEWAY_MEMBER: &str = "add_group_gateway_member";
const REMOVE_GROUP_GATEWAY_MEMBER: &str = "remove_group_gateway_member";
// data service procedure names
const READ_DATA: &str = "read_data";
const LIST_DATA_BY_TIME: &str = "list_data_by_time";
const LIST_DATA_BY_LAST_TIME: &str = "list_data_by_last_time";
const LIST_DATA_BY_RANGE_TIME: &str = "list_data_by_range_time";
const LIST_DATA_BY_NUMBER_BEFORE: &str = "list_data_by_number_before";
const LIST_DATA_BY_NUMBER_AFTER: &str = "list_data_by_number_after";
const GET_DATA_MODEL: &str = "get_data_model";
const READ_DATA_WITH_MODEL: &str = "read_data_with_model";
const LIST_DATA_WITH_MODEL_BY_TIME: &str = "list_data_with_model_by_time";
const LIST_DATA_WITH_MODEL_BY_LAST_TIME: &str = "list_data_with_model_by_last_time";
const LIST_DATA_WITH_MODEL_BY_RANGE_TIME: &str = "list_data_with_model_by_range_time";
const LIST_DATA_WITH_MODEL_BY_NUMBER_BEFORE: &str = "list_data_with_model_by_number_before";
const LIST_DATA_WITH_MODEL_BY_NUMBER_AFTER: &str = "list_data_with_model_by_number_after";
const CREATE_DATA: &str = "create_data";
const CREATE_DATA_WITH_MODEL: &str = "create_data_with_model";
const DELETE_DATA: &str = "delete_data";
const DELETE_DATA_WITH_MODEL: &str = "delete_data_with_model";
// buffer service procedure names
const READ_BUFFER: &str = "read_buffer";
const READ_BUFFER_FIRST: &str = "read_buffer_first";
const READ_BUFFER_LAST: &str = "read_buffer_last";
const LIST_BUFFER_FIRST: &str = "list_buffer_first";
const LIST_BUFFER_LAST: &str = "list_buffer_last";
const CREATE_BUFFER: &str = "create_buffer";
const UPDATE_BUFFER: &str = "update_buffer";
const DELETE_BUFFER: &str = "delete_buffer";
// slice service procedure names
const READ_SLICE: &str = "read_slice";
const LIST_SLICE_BY_NAME: &str = "list_slice_by_name";
const LIST_SLICE_BY_DEVICE: &str = "list_slice_by_device";
const LIST_SLICE_BY_MODEL: &str = "list_slice_by_model";
const LIST_SLICE_BY_DEVICE_MODEL: &str = "list_slice_by_device_model";
const CREATE_SLICE: &str = "create_slice";
const UPDATE_SLICE: &str = "update_slice";
const DELETE_SLICE: &str = "delete_slice";
// log service procedure names
const READ_LOG: &str = "read_log";
const LIST_LOG_BY_TIME: &str = "list_log_by_time";
const LIST_LOG_BY_LAST_TIME: &str = "list_log_by_last_time";
const LIST_LOG_BY_RANGE_TIME: &str = "list_log_by_range_time";
const CREATE_LOG: &str = "create_log";
const UPDATE_LOG: &str = "update_log";
const DELETE_LOG: &str = "delete_log";

// operation error message
const MODEL_NOT_FOUND: &str = "requested model not found";
const MODEL_CREATE_ERR: &str = "create model error";
const MODEL_UPDATE_ERR: &str = "update model error";
const MODEL_DELETE_ERR: &str = "delete model error";
const ADD_TYPE_ERR: &str = "add model type error";
const RMV_TYPE_ERR: &str = "remove model type error";
const CFG_NOT_FOUND: &str = "requested config not found";
const CFG_CREATE_ERR: &str = "create config error";
const CFG_UPDATE_ERR: &str = "update config error";
const CFG_DELETE_ERR: &str = "delete config error";
const DEVICE_NOT_FOUND: &str = "requested device not found";
const DEVICE_CREATE_ERR: &str = "create device error";
const DEVICE_UPDATE_ERR: &str = "update device error";
const DEVICE_DELETE_ERR: &str = "delete device error";
const GATEWAY_NOT_FOUND: &str = "requested gateway not found";
const GATEWAY_CREATE_ERR: &str = "create gateway error";
const GATEWAY_UPDATE_ERR: &str = "update gateway error";
const GATEWAY_DELETE_ERR: &str = "delete gateway error";
const TYPE_NOT_FOUND: &str = "requested type not found";
const TYPE_CREATE_ERR: &str = "create type error";
const TYPE_UPDATE_ERR: &str = "update type error";
const TYPE_DELETE_ERR: &str = "delete type error";
const GROUP_NOT_FOUND: &str = "requested group not found";
const GROUP_CREATE_ERR: &str = "create group error";
const GROUP_UPDATE_ERR: &str = "update group error";
const GROUP_DELETE_ERR: &str = "delete group error";
const ADD_MEMBER_ERR: &str = "add group member error";
const RMV_MEMBER_ERR: &str = "remove group member error";
const DATA_NOT_FOUND: &str = "requested data not found";
const DATA_CREATE_ERR: &str = "create data error";
const DATA_DELETE_ERR: &str = "delete data error";
const DATA_MODEL_NOT_FOUND: &str = "requested data model not found";
const BUFFER_NOT_FOUND: &str = "requested buffer not found";
const BUFFER_CREATE_ERR: &str = "create buffer error";
const BUFFER_UPDATE_ERR: &str = "update buffer error";
const BUFFER_DELETE_ERR: &str = "delete buffer error";
const SLICE_NOT_FOUND: &str = "requested slice not found";
const SLICE_CREATE_ERR: &str = "create slice error";
const SLICE_UPDATE_ERR: &str = "update slice error";
const SLICE_DELETE_ERR: &str = "delete slice error";
const LOG_NOT_FOUND: &str = "requested log not found";
const LOG_CREATE_ERR: &str = "create log error";
const LOG_UPDATE_ERR: &str = "update log error";
const LOG_DELETE_ERR: &str = "delete log error";
